### ISSUE TITLE
WebUI Download Date Picker Bug

### ISSUE THREAD

**Issue by SherifMEldeeb** [roflcoopter/viseron#1019]
Greetings @roflcoopter,

### Issue Description:
Just a little bug to keep In mind the "Download Recording" dialogue which have 2 date time pickers for the download period the start date time gets changed by both pickers.

### Expected Behavior:
Each picker changes the corresponding time.

### Actual Behavior:
End Date picker changes both start and end times.

https://github.com/user-attachments/assets/ccac184b-9d20-4528-bd05-1ddd228ca08f

**Comment by roflcoopter** [comment]
Thanks for reporting, will fix in an upcoming release

**Comment by fluffyspace** [comment]
@roflcoopter you didn't fix it :D thank you for the work you are doing btw

**Comment by roflcoopter** [comment]
You are right, i havent yet :( Since you were kind enough to sponsor i will prioritize this over other issues

**Comment by roflcoopter** [comment]
Should be fixed in #1149, can you try pulling the `dev` tag?

I made it so that selecting one date never alters the other, so it wont set the end date 5 minutes after the start date ever

**Comment by fluffyspace** [comment]
I tried pulling "Viseron - dev - 768c9", issue persists. I will try to modify source code myself today after work and create pull request. Since I find this repo better than Frigate and any other NVR's, it's worth contributing.

**Comment by roflcoopter** [comment]
Ah, builds never ran (it only triggers on changes to the backend, not the frontend, silly me!)
The correct commit should be `bed0be6f`

I started it manually: https://dev.azure.com/viseron/Viseron%20Pipelines/_build/results?buildId=921&view=results

Would love more contributions, so if you can find anything else to work on i'd be happy to help you with any questions you may have.
I often get the question what makes Viseron different from Frigate, if you dont mind me asking, why do you like Viseron more?
I have never tried Frigate myself.

**Comment by fluffyspace** [comment]
Frigate doesn't stream or record audio (their strict design decision, what the ____), didn't have UI responsive for mobile devices (who doesn't have that in 2025?) and basic settings were confusing to me. It detected stationary car again and again, without motion happening... I can't remember other things, but I know it gave me a lot of frustration. Everyone praised it, but I found it awful.

I'll definitely ask you. Where do I ask you?

**Comment by roflcoopter** [comment]
Interesting, thanks for that.
Viseron doesn't do object tracking yet so recording stationary objects could still occur in some circumstances (not without motion tho, depending on the config)

Best is probably to create a new discussion here on Github. I have been meaning to setup a Discord server but never got around to it
