### ISSUE TITLE
dlib facial recognition not working & preventing GUI restart of Viseron

### ISSUE THREAD

**Issue by Maxxell** [roflcoopter/viseron#473]
Hi!
I tried adding dlib facial recognition for one of my cameras by adding this to my configuration:

dlib:
  face_recognition:
    model: cnn
    expire_after: 10
    cameras: 
      frontdoorcam:
        labels:
          - person
    save_unknown_faces: true

But it doesn't work - and I can no longer use the "Restart" button on the GUI configuration page.  I have to use portainer to restart the container. 

I find this error in the logs:
[2023-01-25 11:15:30] [ERROR   ] [root] - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/viseron/__main__.py", line 33, in <module>
    sys.exit(init())
  File "/src/viseron/__main__.py", line 29, in init
    return main()
  File "/src/viseron/__main__.py", line 20, in main
    viseron = setup_viseron()
  File "/src/viseron/__init__.py", line 149, in setup_viseron
    setup_domains(vis)
  File "/src/viseron/components/__init__.py", line 597, in setup_domains
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/viseron/components/__init__.py", line 351, in setup_domain
    domain_module = self.get_domain(domain_to_setup.domain)
  File "/src/viseron/components/__init__.py", line 212, in get_domain
    return importlib.import_module(f"{self._path}.{domain}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/viseron/components/dlib/face_recognition.py", line 17, in <module>
    from .train import train
  File "/src/viseron/components/dlib/train.py", line 9, in <module>
    from sklearn import neighbors
  File "/usr/lib/python3/dist-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/usr/lib/python3/dist-packages/sklearn/base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "/usr/lib/python3/dist-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'

I did follow the directions for training the model on a face. I have 5 pictures here:
\viseron\config\face_recognition\faces\person1\image_of_person1_1.png"

Any ideas why face recognition component is failing?

**Comment by roflcoopter** [comment]
Interesting, what docker container are you using?

**Comment by Maxxell** [comment]
Here's my Docker-Compose, kept as a Stack in Portainer:

version: "2.4"

services:
  viseron:
    image: roflcoopter/amd64-cuda-viseron:latest
    container_name: viseron
    volumes:
      - /home/josh/Docker/viseron/recordings:/recordings
      - /home/josh/Docker/viseron/config:/config
      - /etc/localtime:/etc/localtime:ro
#    devices:
#      - /dev/bus/usb:/dev/bus/usb --privileged
    ports:
      - 8888:8888
    runtime: nvidia

**Comment by roflcoopter** [comment]
I just tried downloading the latest image and it appears to work fine for me.

Could you show me the full log from when restarting the container?

**Comment by roflcoopter** [comment]
Actually, after a few restarts this happened to me as well, seems to be a compatibility issue between the latest numpy and sklearn.
Will pin numpy to an older version which should resolve this

**Comment by Maxxell** [comment]
Hi!  Thanks for reviewing the issue.  I apologize if this is a dumb question - how do I get this working?  I tried stopping the container/stack and redownloading the container image, but still get the same error.

Do I need to wait for you to publish a new version or something?  Sorry, I am kinda new to GitHub.

**Comment by roflcoopter** [comment]
No worries :) I have not had the time to fix it yet, but when I have you will need to download the new version.

I will let you know here when it's ready!

As a side note, I would suggest you look at Compreface instead for face recognition.
It is much more accurate than dlib.
https://viseron.netlify.app/components-explorer/components/compreface

**Comment by Maxxell** [comment]
> As a side note, I would suggest you look at Compreface instead for face recognition.
> It is much more accurate than dlib.
> https://viseron.netlify.app/components-explorer/components/compreface

Thank you for the suggestion.  I looked at the setup but am a little confused.  Am I supposed to run CompreFace as a separate container and then connect Viseron to it?  Or is CompreFace built into Viseron?  I ask because your components setup page for CompreFace shows "recognition_api_key:" in the sample setup, but there is no further mention of that api key.  Where do I get that?

**Comment by roflcoopter** [comment]
Yes that's exactly how you set it up! :)
